export const NEED_CARD_PROMPT_VERSION = "need_card_v2";

type NeedCardPromptInput = {
	sourceText: string;
	sourceUrl: string;
	title: string | null;
};

export function buildNeedCardPrompt(input: NeedCardPromptInput): string {
	const title = input.title?.trim() ? input.title.trim() : "Unknown";
	return [
		"You are an analyst. Read the extracted text and return JSON only.",
		"No markdown. No explanations. No extra keys.",
		"",
		"Classify intent_type first:",
		"- DISCUSSION: opinion, meta talk, \"what do you think\"",
		"- TOOL_DEMAND: asking for a tool/software/automation/solution",
		"- CONSUMER: consumer app/product request",
		"- OTHER: ambiguous, rant, news, link sharing",
		"",
		"Evidence quotes:",
		"- Provide up to 3 short quotes: pain_quote, workaround_quote, ask_quote.",
		"- Each quote must be an exact substring from the input text.",
		"- If not present, output null.",
		"",
		"Scoring rubric (1-5, default 1):",
		"- pain=5: urgent/blocked/repeated failures",
		"- workaround=5: explicit workaround/hack described",
		"- intent=5: explicitly asking for a tool/solution",
		"- wtp=5: mentions budget, pricing, paid plan",
		"- risk=5: heavy compliance/security/complexity",
		"- uncertainty=5: unclear/contradictory requirements",
		"",
		"Output JSON schema:",
		"{",
		'  "kind": "DEMAND" | "NO_DEMAND",',
		'  "intent_type": "TOOL_DEMAND" | "DISCUSSION" | "CONSUMER" | "OTHER",',
		'  "title": string,',
		'  "who": string,',
		'  "pain": string,',
		'  "trigger": string,',
		'  "workaround": string,',
		'  "wtp_signal": "STRONG" | "MEDIUM" | "WEAK" | "NONE",',
		'  "source_url": string,',
		'  "no_demand_reason": string (only when kind=NO_DEMAND),',
		'  "scores": {',
		'    "pain": 1..5,',
		'    "intent": 1..5,',
		'    "workaround": 1..5,',
		'    "audience": 1..5,',
		'    "wtp": 1..5,',
		'    "risk": 1..5,',
		'    "uncertainty": 1..5',
		"  },",
		'  "evidence": {',
		'    "pain_quote": string | null,',
		'    "workaround_quote": string | null,',
		'    "ask_quote": string | null',
		"  },",
		'  "next_action": string[] (1-3 items),',
		'  "score_notes": { pain?: string, intent?: string, workaround?: string, audience?: string, wtp?: string, risk?: string, uncertainty?: string } (optional)',
		"}",
		"",
		"Rules:",
		"- Output JSON only.",
		"- source_url must equal the provided source URL.",
		"- If the text is mainly announcements/news/changelog with no actionable pain/workaround,",
		'  set kind="NO_DEMAND", wtp_signal="NONE", and fill no_demand_reason.',
		"",
		`Source URL: ${input.sourceUrl}`,
		`Page Title: ${title}`,
		"",
		"Extracted Text:",
		"```",
		input.sourceText,
		"```",
		"",
		"Return JSON only.",
	].join("\n");
}
